name: foo
on: [push]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: ./.github/actions/sync-issues
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
